
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvztqndlfpshyclmiqgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52enRxbmRsZnBzaHljbG1pcWd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4OTExNjgsImV4cCI6MjA1ODQ2NzE2OH0.xq_V4O3kkvD6pgzL4bbuhBTT5lzs2w2mk5HWhyRjePA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Define custom types for tables not in Database type
export type Tables = {
  profiles: {
    id: string;
    name: string | null;
    avatar_url: string | null;
    role: string | null;
    created_at: string;
    updated_at: string;
  };
  interview_sessions: {
    id: string;
    user_id: string;
    role_type: string;
    language: string;
    category: string;
    resume_data: any | null;
    created_at: string;
    updated_at: string;
  };
  interview_messages: {
    id: string;
    session_id: string;
    is_bot: boolean;
    content: string;
    created_at: string;
  };
  custom_questions: {
    id: string;
    user_id: string;
    question: string;
    answer: string;
    category: string | null;
    created_at: string;
  };
};
