
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://nvztqndlfpshyclmiqgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52enRxbmRsZnBzaHljbG1pcWd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4OTExNjgsImV4cCI6MjA1ODQ2NzE2OH0.xq_V4O3kkvD6pgzL4bbuhBTT5lzs2w2mk5HWhyRjePA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage
  }
});

// Define types for database schema
export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          user_id: string;
          email: string | null;
          name: string | null;
          full_name: string | null;
          avatar_url: string | null;
          token_identifier: string;
          image: string | null;
          created_at: string;
          updated_at: string | null;
        };
      };
      profiles: {
        Row: {
          id: string;
          name: string | null;
          avatar_url: string | null;
          role: string | null;
          created_at: string;
          updated_at: string;
        };
      };
      interview_sessions: {
        Row: {
          id: string;
          user_id: string;
          role_type: string;
          language: string;
          category: string;
          resume_data: any | null;
          questions_type: string;
          time_limit: number;
          questions_limit: number;
          is_coding_enabled: boolean;
          current_question_count: number;
          start_time: string | null;
          end_time: string | null;
          created_at: string;
          updated_at: string;
        };
      };
      interview_messages: {
        Row: {
          id: string;
          session_id: string;
          is_bot: boolean;
          content: string;
          created_at: string;
        };
      };
      custom_questions: {
        Row: {
          id: string;
          user_id: string;
          question: string;
          answer: string;
          category: string | null;
          created_at: string;
        };
      };
      custom_interview_templates: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          description: string;
          role_type: string;
          language: string;
          category: string;
          questions_type: string;
          time_limit: number;
          questions_limit: number;
          is_coding_enabled: boolean;
          created_at: string;
          updated_at: string;
        };
      };
    };
  };
};

// Define custom types for tables not in Database type
export type Tables = {
  profiles: {
    id: string;
    name: string | null;
    avatar_url: string | null;
    role: string | null;
    created_at: string;
    updated_at: string;
  };
  interview_sessions: {
    id: string;
    user_id: string;
    role_type: string;
    language: string;
    category: string;
    resume_data: any | null;
    questions_type: string;
    time_limit: number;
    questions_limit: number;
    is_coding_enabled: boolean;
    current_question_count: number;
    start_time: string | null;
    end_time: string | null;
    created_at: string;
    updated_at: string;
  };
  interview_messages: {
    id: string;
    session_id: string;
    is_bot: boolean;
    content: string;
    created_at: string;
  };
  custom_questions: {
    id: string;
    user_id: string;
    question: string;
    answer: string;
    category: string | null;
    created_at: string;
  };
  custom_interview_templates: {
    id: string;
    user_id: string;
    title: string;
    description: string;
    role_type: string;
    language: string;
    category: string;
    questions_type: string;
    time_limit: number;
    questions_limit: number;
    is_coding_enabled: boolean;
    created_at: string;
    updated_at: string;
  };
};
